#!/bin/tcsh

# check syntax: run this before pushing anything out to git

echo "-- TSLint --"

tslint -p tsconfig.json
if ("$status" != "0") then
	echo "**** ERRORS; fix TypeScript code before pushing to git"
	exit
endif

echo "-- ESLint --"

cd ts
eslint src/**/*.ts
if ("$status" != "0") then
	echo "**** ERRORS; fix TypeScript code before pushing to git"
	exit
endif
cd ..

echo "All good."
